### ISSUE TITLE
Cant use commands 

### ISSUE THREAD

**Issue by Baburuti** [hsdn/Boss-Helper#3]
Yo

Can't use any of the commands because gives an error 

>[09:50:34.540] [command] ERROR: TypeError: Cannot read property 'toUpperCase' of null
    at getName (C:\Users\yo\AppData\Local\Programs\TeraToolbox\mods\Boss-Helper\index.js:768:33)
    at C:\Users\yo\AppData\Local\Programs\TeraToolbox\mods\Boss-Helper\index.js:188:18
    at Array.forEach (<anonymous>)
    at $none (C:\Users\yo\AppData\Local\Programs\TeraToolbox\mods\Boss-Helper\index.js:186:33)
    at String.subCommandHandler (C:\Users\yo\AppData\Local\Programs\TeraToolbox\mods\command\index.js:315:16)
    at CommandBase.exec (C:\Users\yo\AppData\Local\Programs\TeraToolbox\mods\command\index.js:225:16)
    at hookCommand (C:\Users\yo\AppData\Local\Programs\TeraToolbox\mods\command\index.js:71:31)
    at Object.callback (C:\Users\yo\AppData\Local\Programs\TeraToolbox\mods\command\index.js:81:29)
    at Dispatch.handle (C:\Users\yo\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch.js:414:45)
    at Socket.<anonymous> (C:\Users\yo\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\clients\RealClient.js:40:45)
[09:53:07.181] [dispatch] [boss-helper ng] handle: error running hook for S_SYSTEM_MESSAGE<1>
hook: (anonymous) in boss-helper ng
data: {
  message: '@4398\u000bregionName\u000b@rgn:219\u000bnpcName\u000b@creature:51#1271'
}
error: Cannot read property 'toUpperCase' of null
    at getName (C:\Users\yo\AppData\Local\Programs\TeraToolbox\mods\Boss-Helper\index.js:768:33)
    at getNpc (C:\Users\yo\AppData\Local\Programs\TeraToolbox\mods\Boss-Helper\index.js:757:19)
    at Object.callback (C:\Users\yo\AppData\Local\Programs\TeraToolbox\mods\Boss-Helper\index.js:487:10)
[09:53:22.328] [dispatch] [boss-helper ng] handle: error running hook for S_SYSTEM_MESSAGE<1>
hook: (anonymous) in boss-helper ng
data: {
  message: '@4399\u000bregionName\u000b@rgn:218\u000bnpcName\u000b@creature:84#1278'
}
error: Cannot read property 'toUpperCase' of null
    at getName (C:\Users\yo\AppData\Local\Programs\TeraToolbox\mods\Boss-Helper\index.js:768:33)
    at getNpc (C:\Users\yo\AppData\Local\Programs\TeraToolbox\mods\Boss-Helper\index.js:757:19)
    at Object.callback (C:\Users\yo\AppData\Local\Programs\TeraToolbox\mods\Boss-Helper\index.js:487:10)

**Comment by justkeepquiet** [comment]
Fixed.
